{
 "title": "OracleDB Monitoring - performance and table space stats",
 "description": "Use oracledb exporter for oracle database monitoring. Compared with other dashboards, tablespace monitoring is added, which can be expanded to set tablespace alarms",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(oracledb_up{database=\"$database\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\",database=\"$database\"}"
    }
   ]
  },
  {
   "title": "Process count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_process_count{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - Process count"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\",database=\"$database\"}"
    }
   ]
  },
  {
   "title": "Tablespace status",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(1-oracledb_tablespace_free{instance=\"$host\",database=\"$database\"}/oracledb_tablespace_bytes{instance=\"$host\",database=\"$database\"})"
    }
   ]
  },
  {
   "title": "Active sessions (USER)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$host\",database=\"$database\",status=\"ACTIVE\",type=\"USER\"}"
    }
   ]
  },
  {
   "title": "Execute count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\",database=\"$database\"}"
    }
   ]
  },
  {
   "title": "User rollback",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_rollbacks{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - User rollback"
    }
   ]
  },
  {
   "title": "Concurrent wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - Concurrent wait time"
    }
   ]
  },
  {
   "title": "Commit wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - Commit wait time"
    }
   ]
  },
  {
   "title": "Tablespace usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(1-oracledb_tablespace_free{instance=\"$host\",database=\"$database\"}/oracledb_tablespace_bytes{instance=\"$host\",database=\"$database\"})"
    }
   ]
  },
  {
   "title": "Application wait time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\",database=\"$database\"}\t",
     "legendFormat": "{{descr}} - Application wait time"
    }
   ]
  },
  {
   "title": "Network wait time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\",database=\"$database\"}\t",
     "legendFormat": "{{descr}} - Network wait time"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "Resource utilization - {{resource_name}} "
    }
   ]
  },
  {
   "title": "System I/O wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - System I/O wait"
    }
   ]
  },
  {
   "title": "User I/O wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\",database=\"$database\"}\t",
     "legendFormat": "{{descr}} - User I/O wait"
    }
   ]
  },
  {
   "title": "Configure wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "oracledb_wait_time_configuration{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - Configure wait time"
    }
   ]
  },
  {
   "title": "Scheduler wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "oracledb_wait_time_scheduler{instance=\"$host\",database=\"$database\"}",
     "legendFormat": "{{descr}} - Scheduler wait time"
    }
   ]
  },
  { "title": "Performance collector status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total collection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_scrapes_total{instance=\"$host\",database=\"$database\"}"
    }
   ]
  },
  {
   "title": "Final collection time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\",database=\"$database\"}\t"
    }
   ]
  }
 ]
}